name: Update docs

on:
  pull_request:
    branches: "main"
    types: [opened, ready_for_review, review_requested, assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      # Updates documentation and code formatting
      - name: Update
        run: |
          echo "`date`" >> time.txt
          cat time.txt
      # Commit changes
      - name: Commit files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git commit -am "auto docs"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{github.ref}}
